### ISSUE TITLE
Error when tried to edit existing PTC ad unit

### ISSUE THREAD

**Issue by alexistdev** [futurumclix/futurumclix#21]
I tried to edit ptc ad unit from member advertiser panel, but there is error notice:
"Method Not Allowed"
currently only found on ptc ad unit.

i've checked the error log:
2018-02-18 17:21:50 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /ads/preview/5a89b58c-4aa4-4d5a-94a3-0abe8b6371c3
Stack Trace:
#0 /home/u8468930/public_html/app/Controller/AdsController.php(703): CakeRequest->allowMethod(Array)
#1 [internal function]: AdsController->preview('5a89b58c-4aa4-4...')
#2 /home/u8468930/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AdsController), Array)
#3 /home/u8468930/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /home/u8468930/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AdsController), Object(CakeRequest))
#5 /home/u8468930/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

**Comment by futurumclix** [comment]
Unfortunately I cannot trigger this issue in my test environment. Are you using custom theme? This error means action "preview" was called with HTTP method set wrongly (not to POST, nor PUT). Could you please check if the "form" tag has attribute "method" set to "post"?

**Comment by alexistdev** [comment]
i am using "fresh" template. which file i should check it?

**Comment by futurumclix** [comment]
Not in file, please check in web browser ("inspect element" option or "show page source").

**Comment by alexistdev** [comment]
i found this:
`<form action="/settings/locale/deu" name="post_5ab81e0b244d8204962351" id="post_5ab81e0b244d8204962351" style="display:none;" method="post"><input type="hidden" name="_method" value="POST"/><input type="hidden" name="data[_Token][key]" value="685b3d12a0ec38ec81a80b97cfa1baf889355f09a36e6f73ab883ebc51b28412791e2c9e0ac00083f84bbf07cd1b2bff48df64207273f60af69db756101387b5" id="Token2013235419" autocomplete="off"/><div style="display:none;"><input type="hidden" name="data[_Token][fields]" value="1aa4bfe518b80059e7904edcd3b0830bd7a73c50%3A" id="TokenFields1419235888" autocomplete="off"/><input type="hidden" name="data[_Token][unlocked]" value="" id="TokenUnlocked1132015936" autocomplete="off"/></div></form><form action="/settings/locale/fra" name="post_5ab81e0b24794292807556" id="post_5ab81e0b24794292807556" style="display:none;" method="post"><input type="hidden" name="_method" value="POST"/><input type="hidden" name="data[_Token][key]" value="685b3d12a0ec38ec81a80b97cfa1baf889355f09a36e6f73ab883ebc51b28412791e2c9e0ac00083f84bbf07cd1b2bff48df64207273f60af69db756101387b5" id="Token1851340963" autocomplete="off"/><div style="display:none;"><input type="hidden" name="data[_Token][fields]" value="67cce0376d93fe45438bf5495bb6dbd4ddd5ed25%3A" id="TokenFields2008778673" autocomplete="off"/><input type="hidden" name="data[_Token][unlocked]" value="" id="TokenUnlocked599759979" autocomplete="off"/></div></form><form action="/settings/locale/pol" name="post_5ab81e0b24930201900351" id="post_5ab81e0b24930201900351" style="display:none;" method="post"><input type="hidden" name="_method" value="POST"/><input type="hidden" name="data[_Token][key]" value="685b3d12a0ec38ec81a80b97cfa1baf889355f09a36e6f73ab883ebc51b28412791e2c9e0ac00083f84bbf07cd1b2bff48df64207273f60af69db756101387b5" id="Token501596690" autocomplete="off"/><div style="display:none;"><input type="hidden" name="data[_Token][fields]" value="360f84c61123704cb8250b9f97b3e63a9d792793%3A" id="TokenFields1211865073" autocomplete="off"/><input type="hidden" name="data[_Token][unlocked]" value="" id="TokenUnlocked286410013" autocomplete="off"/></div></form><form action="/settings/locale/rus" name="post_5ab81e0b24abf031166182" id="post_5ab81e0b24abf031166182" style="display:none;" method="post"><input type="hidden" name="_method" value="POST"/><input type="hidden" name="data[_Token][key]" value="685b3d12a0ec38ec81a80b97cfa1baf889355f09a36e6f73ab883ebc51b28412791e2c9e0ac00083f84bbf07cd1b2bff48df64207273f60af69db756101387b5" id="Token715362584" autocomplete="off"/><div style="display:none;"><input type="hidden" name="data[_Token][fields]" value="f7ce377c6cf81b413433bbb5ce21262d133ad994%3A" id="TokenFields1642083987" autocomplete="off"/><input type="hidden" name="data[_Token][unlocked]" value="" id="TokenUnlocked850306879" autocomplete="off"/></div></form><form action="/settings/locale/spa" name="post_5ab81e0b24c63056673553" id="post_5ab81e0b24c63056673553" style="display:none;" method="post"><input type="hidden" name="_method" value="POST"/><input type="hidden" name="data[_Token][key]" value="685b3d12a0ec38ec81a80b97cfa1baf889355f09a36e6f73ab883ebc51b28412791e2c9e0ac00083f84bbf07cd1b2bff48df64207273f60af69db756101387b5" id="Token946327963" autocomplete="off"/><div style="display:none;"><input type="hidden" name="data[_Token][fields]" value="e194e3a9acd82948fc6ad29168824e337977382b%3A" id="TokenFields483286411" autocomplete="off"/><input type="hidden" name="data[_Token][unlocked]" value="" id="TokenUnlocked1292750953" autocomplete="off"/></div></form><form action="/settings/locale/en" name="post_5ab81e0b24dea040784925" id="post_5ab81e0b24dea040784925" style="display:none;" method="post"><input type="hidden" name="_method" value="POST"/><input type="hidden" name="data[_Token][key]" value="685b3d12a0ec38ec81a80b97cfa1baf889355f09a36e6f73ab883ebc51b28412791e2c9e0ac00083f84bbf07cd1b2bff48df64207273f60af69db756101387b5" id="Token952894291" autocomplete="off"/><div style="display:none;"><input type="hidden" name="data[_Token][fields]" value="4b3c087fe813dafecb8b984069b78b34797fc644%3A" id="TokenFields256257629" autocomplete="off"/><input type="hidden" name="data[_Token][unlocked]" value="" id="TokenUnlocked1204509861" autocomplete="off"/></div></form>`

**Comment by alexistdev** [comment]
this problem will be trigered using IDR Currency, i've test it using $ this problem dissappeared
