### ISSUE TITLE
Sent Message From Admin Panel Doesn't Work

### ISSUE THREAD

**Issue by alexistdev** [futurumclix/futurumclix#25]
I've tried to sent message from admin panel:
https://s17.postimg.org/7q04dg42n/sent_message.png

But there is error, both using non smtp and smtp mail, i tried to sent message to single user.

On your demo, there is found error when tried to sent message to single user.

**Comment by futurumclix** [comment]
What kind of error? Is there any message?

**Comment by alexistdev** [comment]
here this message:
`2018-03-25 22:42:04 Error: [SocketException] Invalid email: ""
Request URL: /admin/users/sendMessage
Stack Trace:
#0 /home/u8468930/public_html/lib/Cake/Network/Email/CakeEmail.php(592): CakeEmail->_validateEmail('')
#1 /home/u8468930/public_html/lib/Cake/Network/Email/CakeEmail.php(642): CakeEmail->_setEmail('_from', '', '')
#2 /home/u8468930/public_html/lib/Cake/Network/Email/CakeEmail.php(387): CakeEmail->_setEmailSingle('_from', '', '', 'From requires o...')
#3 /home/u8468930/public_html/app/Model/PendingEmail.php(120): CakeEmail->from('', '')
#4 /home/u8468930/public_html/app/Controller/UsersController.php(2641): PendingEmail->send(Array, 'alexistdev@gmai...')
#5 [internal function]: UsersController->admin_sendMessage()
#6 /home/u8468930/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 /home/u8468930/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /home/u8468930/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 /home/u8468930/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
`

**Comment by alexistdev** [comment]
you can test on fresh installation, it would be an error.
